title: "Rakabima's Cybersecurity Journey"
description: "Documentation of my cybersecurity learning journey"
baseurl: "/my-cybersecurity-journey"
markdown: kramdown

# Collections configuration
collections:
  projects:
    output: true
    permalink: /projects/:path/
  courses:
    output: true
    permalink: /courses/:path/
  ctf-writeups:
    output: true
    permalink: /ctf-writeups/:path/

# Default front matter for collections
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_projects"
    values:
      type: "project"
  - scope:
      path: "_courses"
    values:
      type: "course"
  - scope:
      path: "_ctf-writeups"
    values:
      type: "writeup"